[package]
name = "tea-timer"
version = "0.1.1"
edition = "2021"
description = "A simple and efficient Rust library for measuring and reporting the duration of tasks"
license = "MIT"

[features]
default = ["log"]
log = ["dep:log"]

[dependencies]
log = { version = "0.4", optional = true }
